### ISSUE TITLE
Update to QOpenGL* Classes

### ISSUE THREAD

**Issue by DeveloperPaul123** [mkeeter/fstl#29]
Would be nice to update all uses of `QGL*` classes to use instead `QOpenGL*` classes.

**Comment by DeveloperPaul123** [comment]
@mkeeter I've started implementing this change and got the following results:

![2018-03-08_22-16-25](https://user-images.githubusercontent.com/6591180/37188687-68e3036c-231e-11e8-8267-8b1e6e123924.gif)

Any initial thoughts on what could be going on? All I've done is migrate all `QGL` classes to their `QOpenGL` variant. 

One thing I'll note is that changing `QGLFormat` to `QSurfaceFormat` resulted in me having to remove the call to `setSampleBuffers(true)` since that method doesn't exist for `QSurfaceFormat`. I have yet to find an equivalent class method or a way to set that same setting to true somewhere else.

**Comment by mkeeter** [comment]
That's really weird.

My theory: if you've changed from a `QGLWidget` to a `QOpenGLWidget`, the custom drawing needs to go in `void paintGL() override`, rather than `paintEvent`, and needs to be wrapped in calls to `painter.[begin/end]NativePainting()` (e.g. how I do it [here](https://github.com/libfive/libfive/blob/master/studio/src/view.cpp#L274)).
